### ISSUE TITLE
Publish prepublish

### ISSUE THREAD

**Issue by westwok** [JetBrains/teamcity-dotnet-plugin#10]
I'm using dotnet core 1.0 and I'm getting "No executable found matching command "npm"" when running the publish step.  It appears it's related to the prepublish scripts in the project.json.  Is there something I should be doing that I am not or could this be a bug?

Thanks,
Kevin

**Comment by dtretyakov** [comment]
@westwok, you should ensure that user under which launched TeamCity build agent has a proper `PATH` configuration and you are able to call `npm` from his command prompt.
