### ISSUE TITLE
Dotnet (MSBuild) Properties Issue with Newlines

### ISSUE THREAD

**Issue by bzier** [JetBrains/teamcity-dotnet-plugin#104]
@NikolayPianikov @dtretyakov 
This issue is similar to #81 & #85, but both of those are indicated as being closed/fixed with the latest plugin. I am encountering a very similar issue with plugin `0.9.4`.

Mentioned in #85, the problem seemed to be around the comma in the build step name. In my case, the problem is newlines in a parameter value. We are using a parameter specified in the build configuration for the VCS Root Branch Specification, which requires a newline delimited list of branches. However, that parameter is being included in the `.rsp` file with the newlines included (rather than removed or escaped), which causes MSBuild to fail with:
```
[12:38:28]	[publish] Starting: "C:\Program Files\dotnet\dotnet.exe" publish src\\ProjectName\\ProjectName.csproj --configuration Debug --output bin/PublishOutput @C:\\BuildAgent\\temp\\agentTmp\\c887a2fc76654c51a4ef7951932528d3.rsp
[12:38:28]	[publish] in directory: C:\BuildAgent\work\bcd082293e206f97
[12:38:28]	[publish] MSBUILD : error MSB1008: Only one project can be specified.
[12:38:28]	[publish] Switch: +:refs/heads/(develop)
```

Snippet of the `.rsp` file here:
```
[...]
/p:repo_defaultBranch="refs/heads/production"
/p:repo_watchedBranches="+:refs/heads/(feature/*)
+:refs/heads/(develop)
+:refs/heads/(release/*)
+:refs/heads/(tenant/*)"
/p:settingsBranch="refs/heads/feature/teamcity"
[...]
```

In looking through this, I think we may need to move our parameter out of "System Properties (system.)" so it does not get passed to the build. However, the problem may still be worth looking into. Perhaps escaping or removing newline characters when generating the `.rsp` file and/or validating that no newlines exist in any properties being passed.

**Comment by NikolayPianikov** [comment]
@burnasheva we should also check other special symbols like \r \n \t \b !@#$%^&*()_+=-|/ and etc. All these symbols should be accessible from to msbuild variables. Project to check for system.myVar:

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="Build">
	<Message Text="$(myVar)"/>
  </Target>
</Project>
