### ISSUE TITLE
error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  

### ISSUE THREAD

**Issue by srikanthdasari** [JetBrains/teamcity-dotnet-plugin#105]
Hi,

Help please, i am getting this error, while i am trying to build dotnet core app in teacmcity.

> error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\2.0.2\MSBuild.exe" exists and can be run.

**Comment by dtretyakov** [comment]
@srikanthdasari, could you please describe steps to reproduce it:
* Plugin version
* TeamCity version
* .NET CLI installed on this build agent machine
* part of build log where your build step is failing?

Do you have [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) file in your repository?

**Comment by srikanthdasari** [comment]
@dtretyakov  thanks for responding...

Plugin version is 
![image](https://user-images.githubusercontent.com/7415989/32529277-a0dab404-c405-11e7-9ec7-dedd30e4246c.png)

Teamcity Version - 2017.1.5 (build 47175)

Yes CLI installed in this build agent...and the agent is compatible..

![image](https://user-images.githubusercontent.com/7415989/32529340-03abf7fa-c406-11e7-83f8-e256a11a9024.png)


> C:\Program Files\dotnet\sdk\2.0.2\Microsoft.Common.CurrentVersion.targets(2925,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\2.0.2\MSBuild.exe" exists and can be run.

I dont have global.json

you can find that project in https://github.com/srikanthdasari/WpfSampleProj2.git

**Comment by dtretyakov** [comment]
@srikanthdasari, thanks for repro. You have in this solution WPF project which is [not supported by msbuild in .NET Core SDK](https://github.com/dotnet/cli/issues/6732). You could leave a comment in the mentioned issue to let MSFT know that you need it.

Publishing will work only with `WpfSampleProj2.Lib` and `WpfSampleProj2.Services` projects which is netstandard projects.

Also you could take a look at the possible workaround for WPF project: https://github.com/dotnet/sdk/issues/346#issuecomment-257654120

**Comment by srikanthdasari** [comment]
@dtretyakov thanks its working fine if i remove the WPF project...

but it would be great if i have option which could work with both core and non core projects..

**Comment by dtretyakov** [comment]
@srikanthdasari, for solutions with mixed projects Microsoft recommends to use standalone MSBuild from Visual Studio or Build tools for Visual Studio.

For that you could leverage MSBuild step in your TeamCity build configuration.

**Comment by arabsorkhi** [comment]
I had the same Error.
but By Repairing Visual Studio 2019, 
close VS, delete .vs hidden folder under solution folder and  bin and obj folder then restart your VS to test again.
Fortunately My problem was solved.
