### ISSUE TITLE
Question: Is it possible to install dotnet-cli to TC version 10.0.5?

### ISSUE THREAD

**Issue by vsamma** [JetBrains/teamcity-dotnet-plugin#108]
Is it somehow possible to install the dotnet-cli plugin to an older TeamCity version?

We are currently using TeamCity 10.0.5 (build 42677). We have more than 10 projects with multiple applications/environments and as we want to add one new project, which is on .NET Core 2.0, we would need the dotnet CLI. 

As far as I can understand, we need this plugin and for the plugin we need TC to have a version 2017.1 or higher. 

It would be a risky and a painful task to update the TeamCity version (our license would allow to upgrade to 2017.1.4) and make sure every other project doesn't break or fail just to be able to deploy one .Net Core 2 project. 

So I am asking if there's a possibility to install some kind of version of the dotnet-cli to an older TC version or if maybe someone can suggest some other workaround to build .Net Core 2 projects?

Thanks in advance!

**Comment by NikolayPianikov** [comment]
@burnasheva we should also check other special symbols like \r \n \t \b !@#$%^&*()_+=-|\/ and etc. All these symbols should be accessible from to msbuild variables. Project to check for `system.myVar`:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="Build">
	<Message Text="$(myVar)"/>
  </Target>
</Project>
```

**Comment by vsamma** [comment]
Okay, this thread can be closed because I eventually upgraded the TC and got the plugin to work but just wanted to mention that @NikolayPianikov you probably answered to the wrong question? At least for me your answer does not make sense at all (at least as an answer to my question). :)

**Comment by NikolayPianikov** [comment]
Unfortunately TeamCity 2017+ are only supported

**Comment by NikolayPianikov** [comment]
Sorry I close this ticket by mistake, but ok
