### ISSUE TITLE
Command dropdown and options missing

### ISSUE THREAD

**Issue by svenkle** [JetBrains/teamcity-dotnet-plugin#115]
After updating from SNAPSHOT-20171103111144 to any version I can no longer see the command dropdown. This impacts existing steps and newly created steps.

Before:
![image](https://user-images.githubusercontent.com/3377341/33111122-4b1f3df4-cfa0-11e7-9983-f9f882a73436.png)

After:
![image](https://user-images.githubusercontent.com/3377341/33111147-7fb97a66-cfa0-11e7-8999-483e152e03e0.png)

I've rolled back to the old version and things appear to be working as expected now.

TeamCity Professional 2017.1.5 (build 47175)

**Comment by dtretyakov** [comment]
@svenkle, thanks for reporting it. Could you please try to [download the latest plugin build for TeamCity 2017.1](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityDotnetCorePluginBuild&guest=1) and let me know if this problem was resolved.

**Comment by svenkle** [comment]
Looks like its all working now!
