### ISSUE TITLE
Run already compiled .dll

### ISSUE THREAD

**Issue by renatotkr** [JetBrains/teamcity-dotnet-plugin#117]
Is it possible to run an already compiled  .dll with .NET CLI (dotnet) build step?

I've tried command run and did not work, to work properly there is no need to pass a command

example
dotnet x.dll "parameter"

I can use command line, just wanted to know if there is another way 

Thanks!

**Comment by dtretyakov** [comment]
@renatotkr, thanks for reporting. This use case was mentioned in the https://github.com/JetBrains/teamcity-dotnet-plugin/issues/47#issuecomment-349514037

Currently for that could be used command line build step.
