### ISSUE TITLE
Plugin options are honoured even when not shown in the config UI

### ISSUE THREAD

**Issue by davestephens** [JetBrains/teamcity-dotnet-plugin#136]
When switching through different dotnet cli comands, ie `build`, `restore`, `clean`, the available UI options change accordingly.

However, options that aren't shown for a specific command are still honoured by TeamCity. 

To reproduce: 
- Select `build`, then enter `src` as your Working Directory
- Select `restore`, and the Working Directory box will disappear
- Save the config
- Run a build, and observe that the Working Directory for the dotnet restore step is `src` despite not being shown in the build step configuration UI. 

Running on TeamCity Enterprise 2018.1 (build 58245) on Windows 2012.

**Comment by dtretyakov** [comment]
@davestephens, thanks for reporting. The similar issue was created in the TeamCity tracker:
https://youtrack.jetbrains.com/issue/TW-55717
