### ISSUE TITLE
Apply to multiple projects

### ISSUE THREAD

**Issue by gulbanana** [JetBrains/teamcity-dotnet-plugin#14]
It would be great if this plugin could run dotnet commands on multiple projects, similar to how the Nuget plugin works. E.g. I would like to have a step which does
dotnet test foo
dotnet test bar

and another which does
dotnet pack foo
dotnet pack bar

**Comment by adeel41** [comment]
I am facing the same problem. Although it does says "Projects" but I am not sure which delimiter to use for specifying multiple projects.

**Comment by sachokFoX** [comment]
Have you tried smth similar to `**/project.json`. I am using this for building multiple projects.
`dotnet build **/project.json`

**Comment by pedershk** [comment]
@sachokFoX That only works for dotnet build. dotnet pack doesn't support the globbing pattern natively, unfortunately.

**Comment by brantburnett** [comment]
This limitation is making Nuget CI difficult for me, as well.  As new, related packages are added to a repo, we have to adjust the build configuration.  And then it fails against older branches that don't have those packages.
