### ISSUE TITLE
Run step within docker container not working

### ISSUE THREAD

**Issue by maxjoehnk** [JetBrains/teamcity-dotnet-plugin#142]
We have a couple of Linux Build Agents with just docker, some monitoring and the teamcity agent running on it.
All builds run in docker containers to avoid any issues between multiple agents.
We've tried to run the tests of a new .NET Core project using the .NET CLI (dotnet) runner within a container (mcr.microsoft.com/dotnet/core/sdk:2.2-stretch) to get the test results and test coverage into TeamCity.
This fails with the message 'Cannot find the configuration parameter "jetbrains.buildServer.dotnet.DotnetConstants@7995f765.CONFIG_PATH".'
I've tried to set the missing parameter (as it isn't set in the docker container), but apparently, teamcity doesn't run the build step in a container at all.
For now, we're running the tests just with the command line runner, but seeing the test results in the build overview would obviously be nicer.

**Comment by NikolayPianikov** [comment]
@maxjoehnk what versions of TeamCity and dotnet CLI plugin you using?

**Comment by maxjoehnk** [comment]
TeamCity Professional 2018.2.4 (build 61678)
.NET CLI Support is also version 61678.

**Comment by NikolayPianikov** [comment]
@maxjoehnk Which docker image are you using? Could you share: 
`teamcity-agent.log`
`teamcity-build.log`
from TeamCity agent.

To send these files you could use my address: Nikolay.Pianikov@getbrains.com

**Comment by maxjoehnk** [comment]
**mcr.microsoft.com/dotnet/core/sdk:2.2-stretch** is the image we're using. Running dotnet test within it (on a local machine) works just fine.
Nikolay.Pianikov@jetbrains.com is probably the right address instead of getbrains?

**Comment by NikolayPianikov** [comment]
@maxjoehnk, yes Nikolay.Pianikov@jetbrains.com it is my address, I made a typo

**Comment by maxjoehnk** [comment]
Alright, I've sent you the logs.

**Comment by rsking-mondo** [comment]
We are having the same issue, although with windows containers. We have a windows build agent that only has docker installed. When running dotnet restore, it is failing with

> Cannot find the configuration parameter "jetbrains.buildServer.dotnet.DotnetConstants@1d27477.CONFIG_PATH".

**Comment by rsking-mondo** [comment]
I can confirm that when the .NET Core SDK is installed on the machine, then the dotnet command is run in the docker container.

**Comment by NikolayPianikov** [comment]
[Issue](https://youtrack.jetbrains.com/issue/TW-61085) was created

**Comment by NikolayPianikov** [comment]
Fixed in TeamCity 2019.2
