### ISSUE TITLE
The download link is borken

### ISSUE THREAD

**Issue by stevenxi** [JetBrains/teamcity-dotnet-plugin#147]
The page https://plugins.jetbrains.com/plugin/9190?pr=teamcity is borken, even the site.

Thanks

**Comment by mchechulnikov** [comment]
Thank you for the issue.

It looks like the link to the plugin page on JetBrains Plugins Marketplace works now. 
.NET Support plugin lifecycle is currently strictly bounded by the TeamCity releases itself. This is the reason why there are only old versions on the plugins page.

We are looking forward to publishing plugins more often than the TeamCity release cycle as well.

I'm closing this issue for now. Please feel free to reopen if it doesn't work for you.
