### ISSUE TITLE
dotnet restore returns 401

### ISSUE THREAD

**Issue by mkoziel2000** [JetBrains/teamcity-dotnet-plugin#149]
This problem started happening after we downloaded and installed the latest teamcity patch made available this week. 

The behavior:
running the ".NET" runner with "restore" against a private repo that requires authentication always produces a 401.  

What we've checked:
We checked to verify that the credentials where still valid and that the nuget endpoint could still be hit by a browser with those credentials.  Nothing changed in our build configurations between yesterday and today...the installation of the patch around noon today seem to be when this problem started appearing.  We are using Teamcity as our nuget repo.  I verified that I can perform a "dotnet restore" from the command line within the agent successfully.  

Our workaround at the moment is to let "dotnet build" perform the implicit restore for us.

TeamCity Professional 2019.2.3 (build 72031)

**Comment by NikolayPianikov** [comment]
The related issue is https://youtrack.jetbrains.com/issue/TW-65581

**Comment by NikolayPianikov** [comment]
@mkoziel2000 Please try updating [this plugin](https://github.com/JetBrains/teamcity-dotnet-plugin/files/4525688/dotNetPackagesSupport.zip)
