### ISSUE TITLE
TC is unable to find DotNetCLI_Path when running a .NET core-based Docker image in a cloud agent

### ISSUE THREAD

**Issue by moonolgerd** [JetBrains/teamcity-dotnet-plugin#151]
Docker image is based on .NET Core 3.1
DOTNET_HOME environment variable is set to /usr/share/dotnet
TC cloud agent is created based on the image
TC reports its cloud agent doesn't have DotNetCLI_Path defined:

Incompatible runner: .NET
Unmet requirements: 
DotNetCLI_Path exists

**Comment by moonolgerd** [comment]
Not an issue. Agent still needs to be installed as part of the Docker image

**Comment by NikolayPianikov** [comment]
@moonolgerd You could use this [repo](https://github.com/JetBrains/teamcity-docker-images) as a base to create your own TeamCity images.
