### ISSUE TITLE
Can't run tool install in <custom>

### ISSUE THREAD

**Issue by fatihkaplan** [JetBrains/teamcity-dotnet-plugin#154]
Hi, 
I am trying to install a .net tool via "dotnet tool install" command (in my example, dotnet tool install --global AzureSignTool --version 2.0.17), but contrary to what it says in the [help](https://www.jetbrains.com/help/teamcity/net.html#Custom+Commands), I don't see a field for 'Command Line Parameters' to pass 'tool install..' when I select "custom" in the Command list; I only get the Executables field. I tried passing my command line into the Executables field in different ways, but none worked. We are on version 2020.2.2 (build 85899). Am I missing something, or is this a bug?
Thank you in advance.

**Comment by NikolayPianikov** [comment]
@fatihkaplan for _dotnet_ you should keep the _Executables_ field empty and specify arguments in the field _Command line parameters:_.

**Comment by fatihkaplan** [comment]
> @fatihkaplan for _dotnet_ you should keep the _Executables_ field empty and specify arguments in the field _Command line parameters:_.

@NikolayPianikov Right. And my issue is that there is no Command Line Parameters field when Custom is selected in the Command list.
![Teamcity_dotnetplugin_issue](https://user-images.githubusercontent.com/5797060/110559131-ae157100-8111-11eb-8f50-9262fae58f93.png)

**Comment by NikolayPianikov** [comment]
@fatihkaplan please click on _Show advanced options_

**Comment by fatihkaplan** [comment]
@NikolayPianikov , Thank you; totally user error! I can't believe it didn't occur to me to click on advanced options. I'm glad you created the new issue though, because it definitely would help someone else. Even as a seasoned TeamCity user, I still fell for it.
Once again, thank you very much for your help. And sorry for the late reply; I had to take a couple days off from work.

**Comment by NikolayPianikov** [comment]
@fatihkaplan Always ready to help :)
