### ISSUE TITLE
Cannot find MSBuild path on Teamcity Linux build agent

### ISSUE THREAD

**Issue by Bhodges94** [JetBrains/teamcity-dotnet-plugin#155]
although my DOTNET_HOME was set correctly (/usr/share/dotnet) the documentation shows the detection algorithm for dotnet but why not also for MSBuild?
https://www.jetbrains.com/help/teamcity/msbuild.html
Mine just can't find the MSBuild path at all
Unmet requirements:
MSBuildTools16.0_x64_Path exists

Tried setting env variable in bashrc, buildagent.properties, within the build configuration parameters, I've tried moving the MSBuild folder into /usr/share/dotnet but it just can't find it.
Setup:
ubuntu 20.04 docker container.
TeamCity Enterprise 2020.2 (build 85487).
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET.
Also have Microsoft (R) Build Engine version 16.6.0 for Mono

**Comment by Bhodges94** [comment]
@mkjetbrains can anyone help with this? Or are these issues not monitored anymore?

**Comment by NikolayPianikov** [comment]
@Bhodges94 @Bhodges94 MSBuildTools16.0_x64 is a windows version of MSBuild. It is a part of Visual Studio or Visual Studio [build tools](https://aka.ms/vs/17/release/vs_BuildTools.exe). To run MSBuild tasks on Linux, please choose the cross-platform version of MSBuild in a build step, in this case, [.NET SDK](https://dotnet.microsoft.com/download/dotnet/6.0) is required.

**Comment by Bhodges94** [comment]
@NikolayPianikov , thanks for your reply. I seem to missing this option?
![cross-platform-missing](https://user-images.githubusercontent.com/53040385/142006609-d0403488-8d55-40b1-b177-6759c7ece59c.png)

**Comment by NikolayPianikov** [comment]
Please update the TeamCity

**Comment by NikolayPianikov** [comment]
Please use the .NET runner instead

**Comment by Bhodges94** [comment]
don't worry, i think i've found it 
![image](https://user-images.githubusercontent.com/53040385/142016312-f87a32e6-9539-4a21-9b08-77e9712ffb60.png)
