### ISSUE TITLE
How can I install automatically the .NET Frameworks on an OnPrem Build Agent?

### ISSUE THREAD

**Issue by klacol** [JetBrains/teamcity-dotnet-plugin#157]
Hi, we use TC for many years now. In the last months I learned to know the Github Actions Workflows. They can prepare their build agents via script. So I do not need to prepare any software manually on my agent. The Github Actions Workflow installs automatically the needed software for the builds.

How could we achieve this with TC? I do not want to go remote on every agent for every framework/software that I need; how could this preperation be automated?

Thanks for any tips.

**Comment by NikolayPianikov** [comment]
@klacol hi. You can use Microsoft docker images (search for ".NET SDK" or ".NET Framework SDK" in docker hub) and run builds and tests in these containers via .NET runner. Alternatively, you can run TeamCity agents in a container https://hub.docker.com/r/jetbrains/teamcity-agent. These images already contain the .NET Framework and the .NET SDK.
You can also use the C# script launcher and scripts [like this] (https://github.com/JetBrains/teamcity-csharp-interactive#build-a-project) to install the necessary tools and even run builds.

**Comment by klacol** [comment]
Thanks, I will give it a try.
