### ISSUE TITLE
how to run "dotnet test BuildDrop\Test\**\*.UnitTests.dll"

### ISSUE THREAD

**Issue by jmecosta** [JetBrains/teamcity-dotnet-plugin#164]
Hi

trying to run dotnet test with all dlls found with a give name. works fine in command line. However having some troubles to get this done in the teamcity plugin.

How to do it? thank you
regards 
Jorge Costa

**Comment by mchechulnikov** [comment]
Here is my example that I'm trying
<img width="993" alt="Screenshot 2023-10-31 at 22 09 09" src="https://github.com/JetBrains/teamcity-dotnet-plugin/assets/4894495/a2e915a9-282e-4c7e-af09-a82fe962fe33">
<img width="932" alt="Screenshot 2023-10-31 at 22 09 50" src="https://github.com/JetBrains/teamcity-dotnet-plugin/assets/4894495/d69be160-4a91-4427-8262-e2e76ce0629a">

**Comment by mchechulnikov** [comment]
Closing the issue for now. Please feel free to reopen it if you need any help with this.
