### ISSUE TITLE
restore multiple sources

### ISSUE THREAD

**Issue by dotnetneile** [JetBrains/teamcity-dotnet-plugin#17]
It would be useful to allow a space delimiter like other fields or multi-line like the NuGet Installer runner for multiple sources. The documentation states you can enter source multiple times.

"-s, --source [SOURCE]

Specifies a source to use during the restore operation. This overrides all of the sources specified in the NuGet.config file(s). **Multiple sources can be provided by specifying this option multiple times**."

**Comment by hakan-ronngren** [comment]
Yes, the ability to get sources from both nuget.org and our internal repository is definitely an important ability. Until we can find a way of doing this, we will have to fool TeamCity somehow.
