### ISSUE TITLE
Cannot restore packages from teamcity nuget server

### ISSUE THREAD

**Issue by prabhakarreddy1234** [JetBrains/teamcity-dotnet-plugin#19]
I am using teamcity as my nuget feed. I published 1  dotnet core package using TeamCity CI. I can see that  nuget package has been dropped into the nuget feed folder in Teamcity. But cannot restore that package using visual studio or command line. 

I used `dotnet pack` command.

![image](https://cloud.githubusercontent.com/assets/1984707/18910182/c091ffb8-856e-11e6-8bda-53e90a254314.png)

**Comment by dtretyakov** [comment]
This issue was moved to JetBrains/teamcity-nuget-support#19
