### ISSUE TITLE
Add ability to collect code coverage

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-dotnet-plugin#2]
After running test session plugin should process code coverage results.

**Comment by JhonnyYin** [comment]
This is a really useful tool and I hope code coverage will be added soon!

**Comment by DBugger32** [comment]
dotCover already works in ReSharper for dotnet Core for nUnit code coverage, would be great if TC could use it as well.

**Comment by ashtt** [comment]
dot-cover version 2016.3 is capable of covering dotnet Core but, Team-city comes bundled with dot-cover -2016.2
I am not able to use Team-city's dot-cover for generating the report.

**Comment by niwrA** [comment]
Has anyone raised an issue with TeamCity yet to bundle dotcover 2016.3?

**Comment by NikolayPianikov** [comment]
Hi Jhonny,
You could load a new version of [dotCover](https://www.jetbrains.com/dotcover/download/#section=commandline) manually and use it. TeamCity 2017.1 has the ability to do it simpler - just by selecting the version which you are needed.
After that you should use this [way](https://confluence.jetbrains.com/display/TCD8/Manually+Configuring+Reporting+Coverage) for teamcity-dotnet-plugin.
Also we have this issue [TW-44035](https://youtrack.jetbrains.com/issue/TW-44035)

**Comment by jakerabjohns15** [comment]
Hi @NikolayPianikov, Im currently trying to follow the instructions on the page you linked, but it is not at all clear where I should put the service message, as I do not have an msbuild or ant script, as this is .net core. 

Could you please explain exactly what you meant, or potentially a blog post about this would be a good idea as I have spent a fair few hours now searching in vain for how to achieve this fairly common task. 

Thanks,

Jake.

**Comment by NikolayPianikov** [comment]
@jakerabjohns15 i mean you could create your own proj file for msbuild and use it to run test and to publish a coverage statistics to TeamCity.

As you know the true way to run test for .net core based projects is to use the command line `dotnet test`. But dotnet core plugin is not supported coverage from the box yet and we are working on it.

As workaround you could use the `Visual Studio Tests` runner with options:

Test engine version = `<Custom>` with path `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\TestPlatform\vstest.console.exe`

Additional command line parameters = `/Framework:FrameworkCore10 /TestAdapterPath:.`

dotCover version = 2017.1 or higher

Important to note:
You should install some version of VisualStudio 2017 on the TeamCity agent
You should use `vstest.console.exe` from TestPlatform

**Comment by NikolayPianikov** [comment]
Linked issue: https://youtrack.jetbrains.com/issue/TW-50760
