### ISSUE TITLE
Automatically increment patch number of the package 

### ISSUE THREAD

**Issue by prabhakarreddy1234** [JetBrains/teamcity-dotnet-plugin#20]
I am trying to use TeamCity as nuget server. When i run `dotnet pack` step i want to increment `patch` version automatically.  I think currently it doesn't support.

I could only see that  there is `Verison Suffix` field which replaces `*` with the version.  I think `*` represents release version rather patch version.  Is it possible to update  `patch`. If not can you please add another field or modify current logic to increment `patch`.

**Comment by dtretyakov** [comment]
@prabhakarreddy1234, you can use `text-%build.counter%` as a version suffix or [something else](https://confluence.jetbrains.com/display/TCD10/Configuring+General+Settings#ConfiguringGeneralSettings-BuildNumberFormat).

More details on dotnet pack docs: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-pack

**Comment by prabhakarreddy1234** [comment]
@dtretyakov    `text-%build.counter%  replaces the `*` in the version.  But i want to increment `patch` number.

I am using  `semver` .  Let's say my package is  `1.3.24`. When i want to publish it  teamcity should increment it  so that it should be  `1.3.25` .  Is this possible ?

**Comment by dtretyakov** [comment]
@prabhakarreddy1234, sorry for delay.

dotnet cli tools does not help with it, but by leveraging TeamCity [File content replacer](https://confluence.jetbrains.com/display/TCD10/File+Content+Replacer) build feature you can easily do it.

![image](https://cloud.githubusercontent.com/assets/1025927/19267792/5fe0e760-8fb9-11e6-86ad-611b11af4b5f.png)

Fill in target project file name in *Process files*,  `(\{[^{]*\"version\":\s?\")([^\"]+)(\")` in *Find what* and `$1%build.number%$3` in *Replace with* fields.

**Comment by astef** [comment]
PowerShell build step: https://gist.github.com/astef/68cb9cb4774e82895eb85fcf9d25af77

**Comment by dtretyakov** [comment]
For new csproj files you can use built-in File Content Replacer templates in TeamCity 2017.1, see [TW-49013](https://youtrack.jetbrains.com/issue/TW-49013).
