### ISSUE TITLE
test command not return tests results

### ISSUE THREAD

**Issue by grzes2016** [JetBrains/teamcity-dotnet-plugin#22]
test command not return tests results to Overiew tab, for example return message "Process exited with code 1" when some of test fails:
![teamcity](https://cloud.githubusercontent.com/assets/23076953/19725642/0b6595f8-9b87-11e6-9e5e-cd6bfa7560e3.png)

when all test pass, not added any information about test results.

Tested with:
TeamCity Professional 10.0.1 (build 42078)

**Comment by dtretyakov** [comment]
@grzes2016, thanks for reporting it. We'll provide detailed build info as result of issue #4.
