### ISSUE TITLE
Add support for csproj

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-dotnet-plugin#26]
.NET Core tooling switched to msbuild-based csproj structure from project.json, so we can add a support for such projects. 

More details: https://blogs.msdn.microsoft.com/dotnet/2016/10/19/net-core-tooling-in-visual-studio-15/

**Comment by twurm** [comment]
@dtretyakov any thoughts on when this will be available?  We bit the bullet and upgraded to VS 2017 RC for our ASP.net Core Project and now our TeamCity builds fail when we run pack/publish.

**Comment by dtretyakov** [comment]
@twurm, could you please provide list of errors which you see in pack/publish steps?

**Comment by twurm** [comment]
@dtretyakov below is the error we are seeing:
[Step 3/3] Starting: "C:\Program Files\dotnet\dotnet.exe" pack src/Mx.Web --configuration Debug
[22:39:07]	[Step 3/3] in directory: C:\BuildAgent\work\31ccbb5e0f48106d
[22:39:07]	[Step 3/3] Unable to find a project.json in src/Mx.Web\project.json
[22:39:07]	[Step 3/3] Process exited with code 1
[22:39:07]	[Step 3/3] Step .NET Core (dotnet) failed

**Comment by dtretyakov** [comment]
@twurm, did you installed [.net cli preview3](https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md) on this build agent?
Could you also please execute `dotnet --info` in the working directory, for instance in `C:\BuildAgent\work\31ccbb5e0f48106d`.

**Comment by twurm** [comment]
@dtretyakov thanks for the pointer, Preview 3 was installed, however the agent showed Preview 2 in Agent Parameters\Configuration Parameters.  A reboot of the machine and everything started working!  Thanks for the help!
