### ISSUE TITLE
httpauth for dotnet restore from TeamCity nuget feed

### ISSUE THREAD

**Issue by tofutim** [JetBrains/teamcity-dotnet-plugin#30]
Hi, I do a dotnet restore before my sln is built, and it looks like it wants to nuget restore from it which is fine except I am not sure how to pass in my teamcity credentials as they do not seem to be automatically passed (I am using teamcity as a nuget server). I ended up using guestAuth but prefer httpAuth. Any tips?

**Comment by dtretyakov** [comment]
Hi, thanks for reporting, we need to add support of httpauth for `dotnet restore` command, currently it works for `NuGet Installer` build step.

**Comment by tofutim** [comment]
Mil gracias!

**Comment by dtretyakov** [comment]
Issue in the TeamCity tracker: TW-52337

**Comment by Sovent** [comment]
Hello. Is there any forecast for this feature implementation?

**Comment by dtretyakov** [comment]
@Sovent, it deeply depends on https://github.com/NuGet/Home/issues/5447, so you could comment on it and try to pay MSFT attention on it.
