### ISSUE TITLE
no artifact is being generated from dotnet pack

### ISSUE THREAD

**Issue by mayuanyang** [JetBrains/teamcity-dotnet-plugin#31]
I can see that nuget package is generated, but teamcity doesn't see it as a artifact
###Build log
![image](https://cloud.githubusercontent.com/assets/3387099/21959026/fb811d1e-db06-11e6-9ee3-3fcac070ad34.png)

###Artifact
![image](https://cloud.githubusercontent.com/assets/3387099/21959033/19d8a57a-db07-11e6-9779-d5204d97a5bf.png)

**Comment by dtretyakov** [comment]
@mayuanyang, if you need to keep nuget package [as a build artifact](https://confluence.jetbrains.com/display/TCDL/Build+Artifact) you need to add `output/*.nupkg` directory at the General Settings page of this build configuration.

Please let me know if it works.

**Comment by mayuanyang** [comment]
thanks
