### ISSUE TITLE
Dotnet restore step is not working with net core targeting net framework

### ISSUE THREAD

**Issue by Lechus** [JetBrains/teamcity-dotnet-plugin#35]
http://www.hanselman.com/blog/HowToReferenceAnExistingNETFrameworkProjectInAnASPNETCore10WebApp.aspx

**Comment by dtretyakov** [comment]
@Lechus, it's nuget client issue where in some `dotnet cli` builds it fails to restore packages.
Please leave a comment in the https://github.com/NuGet/Home/issues/4316

**Comment by dtretyakov** [comment]
.NET CLI decided that `dotnet restore` should support restore only for new csproj files, so packages.config will be ignored by design: https://github.com/dotnet/cli/issues/6029 So, please don't hesitate to leave a comment in the mentioned issue.

**Comment by KaranPato** [comment]
Can't access any of these commands
dotnet restore 
dotnet build 
dotnet publish

Getting this error
**java.io.IOException: Cannot run program "sh" (in directory "C:\Program Files (x86)\Jenkins\workspace\KaranPatokar_Jenkins")**

**Comment by dtretyakov** [comment]
@KaranPato, what version of TeamCity and .NET CLI plugin are you using?
Also, please describe steps to reproduce this issue.

**Comment by KaranPato** [comment]
I was not using TeamCity here. Anyways the issue is resolved. Thanks.
