### ISSUE TITLE
Unable to download plugin

### ISSUE THREAD

**Issue by DotNetRockStar** [JetBrains/teamcity-dotnet-plugin#39]
Hello there.  I cannot seem to download the TeamCity plugin.  Is there another link that might work?  Here is the link that I am using to try and download: https://plugins.jetbrains.com/plugin/9190--net-core-support
then scroll down and click [Download] and then I get redirected to this url with the following message:
https://d9ernfkkvx1zk.cloudfront.net/9190/29587/external?updateId=29587&pluginId=9190&pr=teamcity

403 Forbidden

Code: AccessDenied
Message: Access Denied
RequestId: B27FF07AFC64432A
HostId: lVVVOmXIr8pWfMalO/7qCkxXyvUpA/Fnc5VQBmjoyBREHZ67OpJqHgmiAo0fGG1sd2oq7r9nMBw=

Any help would be greatly appreciated

**Comment by dtretyakov** [comment]
Thanks for reporting, please use [following link](https://teamcity.jetbrains.com/app/rest/builds/buildType:TeamCityDotnetCorePluginBuild,branch:default:any,tag:release/artifacts/content/dotnet-core-plugin.zip?guest=1) to download plugin.

**Comment by dtretyakov** [comment]
The issue in the plugins repository and it will be fixed in 2 hours.

**Comment by dtretyakov** [comment]
Fixed.
