### ISSUE TITLE
dotnet restore

### ISSUE THREAD

**Issue by capiono** [JetBrains/teamcity-dotnet-plugin#40]
I have a private NuGet server. I can restore packages from VS and via command line from my package source. 

However, what I run in team city, I get this error:

> [06:56:44][Step 1/3]   Restoring packages for C:\TeamCity\buildAgent\work\279c3e8f3593f219\src\myproject\app.csproj...
> [06:56:45][Step 1/3]   Retrying 'FindPackagesByIdAsyncCore' for source 'http://appshard1/nuget/FindPackagesById()?id='App.Core''.
> [06:56:45][Step 1/3]   Response status code does not indicate success: 504 (Unknown Host).
> [06:56:45][Step 1/3]   Retrying 'FindPackagesByIdAsyncCore' for source 'http://appshard1/nuget/FindPackagesById()?id='App.Core.ViewModel''.
> [06:56:45][Step 1/3]   Response status code does not indicate success: 504 (Unknown Host).
> [06:56:45][Step 1/3]   Retrying 'FindPackagesByIdAsyncCore' for source 'http://appshard1/nuget/FindPackagesById()?id='App.Core.Identity''.
> [06:56:45][Step 1/3]   Response status code does not indicate success: 504 (Unknown Host).

when I enter this: 

> http://appshard1/nuget/FindPackagesById()?id='App.Core.ViewModel'

in the browser directly it works just fine. 

I'm using:
      dotnet SDK 1.0.3
       TeamCity dotnet Plugin: 0.8.1 

Thanks.

**Comment by dtretyakov** [comment]
@capiono, you need to check network settings on the build agent machine. According to the log it could not resolve your private nuget server name `appshard1` into ip address.

For that try to execute `nslookup appshard1` on the build agent machine under the same user account which is used to tun TeamCity agent under and check output. If it fails then contact your network administrators to properly configure dns servers on the build agent machine.

**Comment by capiono** [comment]
The DNS is proper configured and nslookup, returned the right info

**Comment by dtretyakov** [comment]
@capiono, ok, maybe you are using proxy server to access target nuget server?
In case of improper configuration it can fail with `504 (Unknown Host)` error.

Please take a look at the following questions:
* https://stackoverflow.com/questions/28288328/nuget-the-remote-server-returned-an-error-504-gateway-timeout 
* https://stackoverflow.com/questions/11553591/visual-studio-c-nuget-unable-to-connect-to-remote-server

To check whether internet & proxy settings works fine for nuget you could navigate to the directory `C:\TeamCity\buildAgent\work\279c3e8f3593f219\` and execute one of the following commands:
* `dotnet restore src\myproject\app.csproj`
* `nuget restore src\myproject\app.csproj` via [nuget command line](https://dist.nuget.org/).

**Comment by capiono** [comment]
Got the same error after running the dotnet restore command

**Comment by dtretyakov** [comment]
@capiono, to check environment could you try to login to this machine under the same user account which is used to run TeamCity build agent. Then navigate to the checkout directory like `C:\TeamCity\buildAgent\work\279c3e8f3593f219\` from the command line and execute `dotnet restore` for your project like `dotnet restore src\myproject\app.csproj`.

If you are running TeamCity build agent service under Local System account please change it to your user account where properly works connection in the browser.

**Comment by NikolayPianikov** [comment]
@capiono any updates about this issue?

**Comment by capiono** [comment]
It is still not working. Getting the same error.

**Comment by capiono** [comment]
Moving my local nuget to the same box I have team city, resolved this issue.
