### ISSUE TITLE
Check compatibility with .NET Core 2.0.0

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-dotnet-plugin#42]
We need to ensure that all new features from .NET Core 2 works fine:
https://github.com/dotnet/announcements/issues/17

**Comment by DannyAllegrezza** [comment]
Hi @dtretyakov,

Now that 2.0 is out in final release form, do you have a status update of TC support for this plugin?

**Comment by davestephens** [comment]
It looks like most/all of the functionality is in the source, but the version on the Jetbrains plugin website is the one from March this year. Any news on a release guys?

**Comment by NikolayPianikov** [comment]
I've checked 2.0 looks compatible. @davestephens some last changes: dotCover support, `dotnet clean` command, tests integration, much better presentation of a build output
