### ISSUE TITLE
Check compatibility with popular test frameworks

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-dotnet-plugin#5]
We can check integration with a following test frameworks:
- xunit
- nunit
- mstest

**Comment by SaltyDH** [comment]
This is probably way too soon but with NUnit support now available via the dotnet test cli, what's the best way to pass the results through to TeamCity so that the test run results are captured? Currently it looks like it returns the number of failed tests as the error code.

**Comment by dtretyakov** [comment]
@SaltyDH, we created an issue in nunitlite to return back teamcity support:
https://github.com/nunit/nunit/issues/1224

You can vote for it.

**Comment by dtretyakov** [comment]
To provide tests reporting for different frameworks can be used [TeamCity VSTest adapter](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter).

All that you need is to add a reference for [`TeamCity.VSTest.TestAdapter`](https://www.nuget.org/packages/TeamCity.VSTest.TestAdapter) nuget package.

**Comment by NikolayPianikov** [comment]
Now [TeamCity VSTest adapter](https://github.com/JetBrains/TeamCity.VSTest.TestAdapter) is not required. Plugin uses integration package from-the-box. Integration of xunit/nunit/mstest was checked
