### ISSUE TITLE
NuGet restore is looking in user directory

### ISSUE THREAD

**Issue by poteb** [JetBrains/teamcity-dotnet-plugin#6]
I've installed the plugin and I'm trying to build my project with the .NET Core (dotnet) runner. It's failing right away because it's looking for a dll from a package in my users directory.
```
[09:04:13][Step 2/2] Starting: "C:\Program Files\dotnet\bin\dotnet.exe" build LevApi
[09:04:13][Step 2/2] in directory: E:\TeamCity\buildAgent4\work\b62b6825dfad2144
[09:04:14][Step 2/2] Could not find a part of the path 'C:\Windows\system32\config\systemprofile\.nuget\packages\System.Numerics.Vectors\4.1.1-beta-23516\lib\portable-net45+win8\System.Numerics.Vectors.dll'.
[09:04:14][Step 2/2] Process exited with code 1
[09:04:14][Step 2/2] Step Build LevApi (.NET Core (dotnet)) failed
```
This is build with a build agent running under Local System account. I have another build agent running under my account, when I use that it's trying to find the dll in my users directory.
```
[Step 2/2] Could not find a part of the path 'C:\Users\dfpsb\.nuget\packages\System.Numerics.Vectors\4.1.1-beta-23516\lib\portable-net45+win8\System.Numerics.Vectors.dll'.
```
I can build other non-Core .NET projects just fine.
I'm at a loss if the problem is with NuGet 3.4.3, the ASP.NET Core installation or the plugin.

I'm using the latest runtime:
```
C:\Windows\system32>dnvm list

Active Version           Runtime Architecture Location                                                                            Alias
------ -------           ------- ------------ --------                                                                            -----
  *    1.0.0-rc1-update2 clr     x86          C:\Users\dfpsb\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin\dnx.exe\runtimes default
```

**Comment by dtretyakov** [comment]
@poteb, could you try to use `dotnet restore` build step before `dotnet build` to restore packages?

Also, if you want to arrange target nuget packages location you can specify path in the advanced build step settings.

Note: dnvm works with DNX projects and dotnet with .NET CLI projects.

**Comment by poteb** [comment]
@dtretyakov That worked like a charm, running `dotnet restore` with a Command Line and Working directory set to the root of the project.
I thought it would do that automatically, like Visual Studio does when you change something in your project.
Thank you so much.

**Comment by tofutim** [comment]
Just want to say that this thread saved my hide. Thanks.
