### ISSUE TITLE
dotnet_Path exists error

### ISSUE THREAD

**Issue by ChantayOsborne** [JetBrains/teamcity-dotnet-plugin#7]
Per the documentation, we have the DOTNET_HOME environment variable configured, but we still have the "Unmet requirements: dotnet_Path exists" error on the build agent. Visual Studio and .NET core were all installed from this link: https://www.microsoft.com/net/core#windows

**Comment by dtretyakov** [comment]
@ChantayOsborne, please make sure that you have configured `PATH` or `DOTNET_HOME` under build agent user, and value looks like `C:\Program Files\dotnet\`. Then you should restart TeamCity build agent. After agent connection, you can ensure that environment variables are properly propagated to the build agent at the Agent Parameters => Environment Variables page.

When it is properly configured you will see at the Agent Parameters => Configuration Parameters defined `dotnet_Path` variable.

**Comment by ChantayOsborne** [comment]
I've got the DOTNET_HOME variable, and it shows under Agent Parameters -> Environment Variables, but I'm still getting Unmet Requirements errors. I've tried restarting the agent, the entire TeamCity server, and rebooting the box. What should I check next?

![image](https://cloud.githubusercontent.com/assets/19270594/15870584/fd75fcf0-2cad-11e6-8c6d-e63a25504124.png)

**Comment by dtretyakov** [comment]
@ChantayOsborne, thanks for pointing out, .NET CLI package structure has been changed, so you can download [latest plugin build](https://teamcity.jetbrains.com/repository/download/TeamCityDotnetCorePluginBuild/.lastSuccessful/dotnet-core-plugin.zip?guest=1) to resolve it.

**Comment by ChantayOsborne** [comment]
Perfect, that fixed the issue. Thank you!

**Comment by oliverjanik** [comment]
So what is needed to get the agent going?

**Comment by dtretyakov** [comment]
@oliverjanik, TeamCity build agent detects .NET CLI availability while starting. Before that you need to [install .NET Core SDK](https://www.microsoft.com/net/download/core) on the build agent machine.

**Comment by oliverjanik** [comment]
I have done that, but I still needed to set DOTNET_HOME manually?

**Comment by dtretyakov** [comment]
@oliverjanik, while discovering `dotnet` location the plugin considers following locations for user under which TeamCity build agent is running:
* `PATH` environment variable  which is usually updated after .NET CLI installation
* `DOTNET_HOME` if you need to use dotnet CLI location which is not included in `PATH` variable.

Note: It your're running TeamCity build agent under SYSTEM account you have to update PATH for SYSTEM account like that: https://stackoverflow.com/q/32068893 and restart system.

If it still fails please share details from the %build agent name% -> Agent Parameters -> Environment Variables page.

**Comment by oliverjanik** [comment]
Right, restarting the service would've done it :-) Thanks for your explanation. I hope other people will find it useful, too.

**Comment by ormico** [comment]
I'm having this same problem but on Ubuntu. Is this plugin compatible with Ubuntu/Linux agents or just Widnows agents. I'm trying to compile a asp.net core app and then package in a linux docker container. my Windows agent stopped working after a recent windows update affecting Windows 10 & nested virtualization. thought I would try running it on Ubuntu instead.

**Comment by oceaneLonneux** [comment]
Currently bumping on this. 

dotnet is running on the Debian server. I have .NET Core on 2.1.603. DOTNET_HOME (and I tried DOTNET_ROOT before) is set on /home/teamcity/dotnet. Path has /home/teamcity/dotnet in it.
Teamcity doesn't pick up dotnet, and therefore, doens't allow Octopus releases. 

We have the error message "jetbrains.buildServer.AGENT - Octopus can not run on agent with Unix and without Octo.exe or DotNET". 
Currently working with the support for that, surprised to see other people actually had that issue as well
