### ISSUE TITLE
Installed Dotnet Core plugin and selected .Net build runner then nothing

### ISSUE THREAD

**Issue by gHoodlum** [JetBrains/teamcity-dotnet-plugin#76]
I have installed the Dotnet-core-plugin. After following a similar issue (TW-51538) I assume that after selecting the .Net build runner I should see configuration options, but after selecting it nothing happens. Configuration options don't show up and I can't save the new configuration either. Options do show up for every other build runner. We have TeamCity Enterprise 2017.1.4 (build 47070) installed. 
Thanks.

**Comment by NikolayPianikov** [comment]
@gHoodlum could you share steps to reproduce and screenshot of you build step

**Comment by gHoodlum** [comment]
Things have changed a little since I first posted this. I was trying to make changes to an existing project when I was getting this issue. I deleted the project and started from scratch. 

First, I create a new project from a repository URL.
It automatically discovers 3 build steps. 
![image](https://user-images.githubusercontent.com/26724675/30879480-20f963e0-a2c5-11e7-936e-3d0c234560b2.png)

I select the 2 .Net steps. At this point the project will build. The issue now is, if I try to edit one of the build steps I still don't get all of the configuration options (image below). BTW, I don't see any javascript errors in the console so I assume you are building the html on the server side.

![buildstepmissingconfigoptions](https://user-images.githubusercontent.com/26724675/30879007-d46e69f4-a2c3-11e7-90ba-60f5bbde13b0.PNG)

There is also the issue of creating a nuget package. If I try to manually create a step to do so and select the .Net runner no other config options come up.
![newbuildstep](https://user-images.githubusercontent.com/26724675/30879171-4a3e2f7a-a2c4-11e7-939f-b1f8350e6398.PNG)

**Comment by NikolayPianikov** [comment]
@gHoodlum thank you for info, looks like a bug, I am going to watch on it tomorrow

**Comment by NikolayPianikov** [comment]
@gHoodlum what browser and what version did you use?

**Comment by gHoodlum** [comment]
@NikolayPianikov I am using FireFox 55.0.3

**Comment by NikolayPianikov** [comment]
@gHoodlum could you try [it](https://teamcity.jetbrains.com/repository/download/TeamCityDotnetCorePluginBuild/1182094:id/dotnet-core-plugin.zip)

**Comment by gHoodlum** [comment]
@NikolayPianikov I tried creating a new project from scratch. When editing or adding build steps I get the following:

![image](https://user-images.githubusercontent.com/26724675/30983833-2dd892e2-a451-11e7-8238-bf5775a957be.png)

Do I need to download and install anything new?

**Comment by NikolayPianikov** [comment]
@gHoodlum did you install [this](https://teamcity.jetbrains.com/repository/download/TeamCityDotnetCorePluginBuild/1182094:id/dotnet-core-plugin.zip) version?

**Comment by gHoodlum** [comment]
@NikolayPianikov Sorry, I missed the link in the first message. I installed it and now I can see the configuration options. I will move forward and let you know if there are any more issues that pop up. Thanks for your help.

**Comment by NikolayPianikov** [comment]
@gHoodlum thank you very match! Yes please any issues or suggestions
