### ISSUE TITLE
Setting up Dependent Projects in the Build

### ISSUE THREAD

**Issue by ChantayOsborne** [JetBrains/teamcity-dotnet-plugin#8]
The build is now working for stand alone projects, but how do I go about setting up the build in such a way where dependencies are handled? For instance, I have a project called "Location", which has a dependency on another project called "Google". That's defined in my project.json file:

"dependencies": {
    "Microsoft.Net.Http": "2.2.22",
	"Newtonsoft.Json": "6.0.6",
	"Google" :  "1.0.0"
  }

How do I make sure that the build process sees Google and knows where it is?

**Comment by dtretyakov** [comment]
@ChantayOsborne .NET CLI tools should recoursevely resolve your project structure, so you can leave blank or manually specify project paths.
