### ISSUE TITLE
dotnet restore/publish step failure

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-dotnet-plugin#81]
Originally from https://plugins.jetbrains.com/plugin/9190--net-core-support by @Dobryak.

Whenever I try to use this plugin - it fails due to the file with rsp extension attached to command. For example:
```
[12:12:06][Step 3/4] Starting: "C:\Program Files\dotnet\dotnet.exe" restore --verbosity Diagnostic @C:\\t\\1\\buildTmp\\81a257c2f7fa4275a9f660012a89b9da.rsp [12:12:06][Step 3/4] in directory: C:\w\1\7686684696a3c6f9 [12:12:06][Step 3/4] error: @C:\\t\\1\\buildTmp\\81a257c2f7fa4275a9f660012a89b9da.rsp
```
If I run the same command on server in console - it also fails. If I remove RSP file - restore command goes well.

Same goes with publish:
```
[Step 5/5] Starting: "C:\Program Files\dotnet\dotnet.exe" publish C:\\w\\1\\7686684696a3c6f9\\src\\project\\project.json --configuration Release --output C:\\t\\1\\buildTmp\\project\\ @C:\\t\\1\\buildTmp\\0097828f9fab406b89f0b5d8c2a0ce6a.rsp [12:24:30][Step 5/5] in directory: C:\w\1\7686684696a3c6f9 [12:24:31][Step 5/5] Specify --help for a list of available options and commands. [12:24:31][Step 5/5] Unrecognized command or argument '@C:\\t\\1\\buildTmp\\0097828f9fab406b89f0b5d8c2a0ce6a.rsp' [12:24:31][Step 5/5] Process exited with code 1 [12:24:31][Step 5/5] Step Publish (.NET) failed
```
What is this rsp file, what it does and how to remove it?

**Comment by NikolayPianikov** [comment]
which version of dotnet/SDK you are using?

**Comment by akuryan** [comment]
1.0.0-preview2-003131

**Comment by NikolayPianikov** [comment]
@akuryan prerelease versions are not supported
could you update your [dotnet CLI/SDK](https://www.microsoft.com/net/download/core)?

**Comment by akuryan** [comment]
Aha, clear. I will try to do this :), but not sure when it will be done. BTW, can this be mentioned at readme.md at root of repository? Or maybe I missed this somewhere :(

**Comment by NikolayPianikov** [comment]
@akuryan I am going to update reamde

**Comment by NikolayPianikov** [comment]
@akuryan could you close this ticket if updating solved your issue?

**Comment by akuryan** [comment]
It was created by @dtretyakov  - I could not close it. But, updating solves an issue, so this one can be closed

**Comment by cubanx** [comment]
I'm getting this error with the plugin using .Net Core 2.0.0. Should I file a new issue?

**Comment by dtretyakov** [comment]
@cubanx, could you please share the teamcity .NET CLI plugin version and generated command line from the build log like in the first comment: `Starting: "C:\Program Files\dotnet\dotnet.exe" ...` ?

**Comment by cubanx** [comment]
It's not just with restore/publish, it seems to be a lot of the commands. Here's the requested info with just a build:
```[Step 1/3] Starting: "C:\Program Files\dotnet\dotnet.exe" build D:\\BuildAgent\\work\\fdddf0abe2803dc0\\CineNet.OneService\\CineNet.OneService.csproj --configuration Release @D:\\BuildAgent\\temp\\buildTmp\\afd15476265048da933bc45a096cd85b.rsp
[20:13:39][Step 1/3] in directory: D:\BuildAgent\work\fdddf0abe2803dc0
[20:13:40][Step 1/3] MSBUILD : error MSB1006: Property is not valid.
[20:13:40][Step 1/3] Switch:  Pack
[20:13:40][Step 1/3] 
[20:13:40][Step 1/3] For switch syntax, type "MSBuild /help"```

Let me know if you need more

**Comment by cubanx** [comment]
Also, it works with this Command Line step:
```dotnet.exe build %solution_name%\%solution_name%.csproj -c Release```

**Comment by NikolayPianikov** [comment]
it seem to be fixed here #85, just update your plugin

**Comment by NikolayPianikov** [comment]
@cubanx any updates?

**Comment by 1015450578** [comment]
I'm getting this error with the plugin using .Net Core 2.0.0. Any suggestion?

**Comment by dtretyakov** [comment]
@1015450578, could you please provide a corresponding build log with a command line and error message?

**Comment by orihomie** [comment]
I've updated sdk version (on a local machine where "dotnet test" runs) to a 3.1 and that still happens
>	[dotnet test] Starting: C:\Program Files\dotnet\dotnet.exe test .\MySln.sln --filter "Category!=SchemaTests" --configuration Release --no-build --no-restore -- xunit.parallelizeAssembly=true -- xunit.parallelizeTestCollections=true -- xunit.maxParallelThreads=-1 @D:\buildAgent1\temp\agentTmp\1.rsp
[16:25:27]	[dotnet test] in directory: D:\buildAgent1\work\e49451ace4a6eb8d
[16:25:27]	[dotnet test] 
[16:25:27]	[dotnet test] Welcome to .NET Core 3.1!

> SDK Version: 3.1.201

Error is 
>	[dotnet test] One or more runsettings provided contain invalid token

If I'll run that command locally or on a build machine without "@D:\buildAgent1\temp\agentTmp\1.rsp" - all will be ok.
When I run exactly same command on a build machine- it just opens .rsp file.

**Comment by orihomie** [comment]
Seems also to be related to https://github.com/JetBrains/teamcity-dotnet-plugin/issues/116

**Comment by NikolayPianikov** [comment]
@orihomie what version of TeamCity are you using?

**Comment by orihomie** [comment]
2019.2.1

**Comment by NikolayPianikov** [comment]
Looks like this issue was fixed. Is it possible to upgrade TeamCity to 2019.2.2?

**Comment by orihomie** [comment]
> Looks like this issue was fixed. Is it possible to upgrade TeamCity to 2019.2.2?

Sry, how did you figured that out?
We'll try to upgrade latter today and then check how that works.

**Comment by NikolayPianikov** [comment]
We just moved custom arguments to the end of list of arguments. Please let me know results

**Comment by orihomie** [comment]
Did you mean this?
![image](https://user-images.githubusercontent.com/29889683/78799521-eb81f380-79c2-11ea-87f9-07d94b249277.png)

**Comment by NikolayPianikov** [comment]
``` -- xunit.parallelizeAssembly=true -- xunit.parallelizeTestCollections=true -- xunit.maxParallelThreads=-1```

**Comment by NikolayPianikov** [comment]
Actually yes, all custom args

**Comment by orihomie** [comment]
No, that wont work

**Comment by NikolayPianikov** [comment]
I just checked
![1](https://user-images.githubusercontent.com/11720017/78801776-c2169700-79c5-11ea-81e1-bdd5fd256a3f.png)

**Comment by orihomie** [comment]
Can you show the end of 3d string? Isnt there .rsp file?

**Comment by NikolayPianikov** [comment]
```
.NET SDK 2.1.802 C:\Program Files\dotnet\dotnet.exe test xunittests.csproj "@C:\Projects\TeamCity\teamcity\.idea_artifacts\agent deployment debug\temp\agentTmp\1.rsp" -- xunit.parallelizeAssembly=true -- xunit.parallelizeTestCollections=true -- xunit.maxParallelThreads=-1
```

**Comment by orihomie** [comment]
No specific option enabled? Adding .rsp file disabled by default in new version of teamcity?

**Comment by NikolayPianikov** [comment]
There are no any tricky parameters. No, we cannot avoid using .rsp. We moved custom arguments to the end of list of arguments, after all arguments (and after .rsp). The .rsp file - just a text file with the same arguments. The length of command line has a limitation. To meet this limitation we should use .rsp. Your build fails because of your version of .NET plugin the additional xunit arguments (after ` -- `) was placed before the dotnet `test` command arguments

**Comment by orihomie** [comment]
Yep, that worked
