### ISSUE TITLE
Unable to publish to local TeamCity nuget feed

### ISSUE THREAD

**Issue by gHoodlum** [JetBrains/teamcity-dotnet-plugin#84]
Here is a new issue I am running into. I added a Nuget Pack build step to publish to our local Nuget feed, but the process errors out with a message of "Unable to find ''. Make sure the project has been built." I have attached the log and an image of the build configuration.

[ObjectMapper.Core_Build_5.log](https://github.com/JetBrains/teamcity-dotnet-plugin/files/1349531/ObjectMapper.Core_Build_5.log)

![image](https://user-images.githubusercontent.com/26724675/31087320-3600fd60-a762-11e7-8e1c-3d359e57555f.png)

Thanks.

**Comment by gHoodlum** [comment]
@NikolayPianikov, any help?

**Comment by NikolayPianikov** [comment]
@gHoodlum sorry for delay, I've assign a person who can help

**Comment by NikolayPianikov** [comment]
@gHoodlum try using the newest version of NuGet from [this page](https://www.nuget.org/downloads). Looks like 3.4.3 is too old for the new .net core project model

**Comment by dtretyakov** [comment]
@gHoodlum, standalone NuGet client works with .NET Core projects starting with version 3.5.
