### ISSUE TITLE
dotnet restore produces MSB1006 after upgrade to latest

### ISSUE THREAD

**Issue by cdibbs** [JetBrains/teamcity-dotnet-plugin#85]
Following an upgrade to SNAPSHOT-20171002131949, we are unable to run `dotnet restore`. It throws the following error:
```
Starting: "C:\Program Files\dotnet\dotnet.exe" restore E:\\BuildAgent\\work\\3f98e6a4b94cfd12\\AppDev.IdentityServer4.sln --configfile nuget.config @E:\\BuildAgent\\temp\\buildTmp\\cc7e202733bc4a7bb36c001ee60ea1f7.rsp
in directory: E:\BuildAgent\work\3f98e6a4b94cfd12
MSBUILD : error MSB1006: Property is not valid.
Switch: Test and Deploy
```

We use TeamCity 2017.1.2 and dotnet 2.0.0.

**Comment by cdibbs** [comment]
Found the issue. Within the .rsp file, the build configuration name was passed in like so:

```
/p:teamcityBuildConfName=Id Srv 4 (Test) Build, Test and Deploy"
```
Seeing how the error message indicated that it thought "Test and Deploy" was its own switch, I removed the comma from our build configuration name, and the build worked fine.

**Comment by NikolayPianikov** [comment]
@cdibbs fixed, just update your plugin
