### ISSUE TITLE
Does not work properly with publish-iis tool

### ISSUE THREAD

**Issue by Kavorka79** [JetBrains/teamcity-dotnet-plugin#9]
**Project.json**

``` javascript
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  },
```

**Settings**
Projects: src/foo
Configuration: Release
output: published-app

generats command: `"C:\Program Files\dotnet\dotnet.exe" publish src/foo --configuration Release --output published-app`

Expected:
tranformation of web.config

Actual:
`Could not find a part of the path 'D:\TeamCity\buildAgent\work\c0b1debfe88f0b47\src\foo\published-app\web.config'.`

Works if you run build step as command line with command: 

``` cmd
cd src\pixie
dotnet publish -o ..\..\published-app -c Release
```

**Comment by dtretyakov** [comment]
@Kavorka79, thanks for report. 
We will update tooling support to reflect recent changes in the .net core 1.0 release.

**Comment by kf-josephmegkousoglou** [comment]
Is there an update on this?

**Comment by dtretyakov** [comment]
Actually it is caused by `dotnet publish` command error: https://github.com/dotnet/cli/issues/3528, https://github.com/dotnet/cli/issues/3679

**Comment by dtretyakov** [comment]
`dotnet publish` works fine with absolute paths, so as a workaround you can prepend your output path by `%teamcity.build.workingDir%` [build parameter](https://confluence.jetbrains.com/display/TCDL/Predefined+Build+Parameters).

@Kavorka79, in your case it will look like `%teamcity.build.workingDir%/published-app`
