### ISSUE TITLE
Duplicated number of tests

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-dotnet-plugin#91]
While executing `dotnet test` for project [WindowsAzure](https://github.com/dtretyakov/WindowsAzure) in the build log logged correct number of executed tests, but on the Tests tab displayed duplicated entries:
```
[15:26:17][Step 2/2] Total tests: 413. Passed: 341. Failed: 0. Skipped: 72.
[15:26:17][Step 2/2] Test Run Successful.
[15:26:17][Step 2/2] Test execution time: 2.7989 Seconds
```

![image](https://user-images.githubusercontent.com/1025927/31549065-467a60ea-b02d-11e7-8f02-6f0eb4a08df8.png)

**Comment by dtretyakov** [comment]
The same happens with `dotnet vstest` command.

**Comment by dtretyakov** [comment]
It seems that it was caused by data races while writing output:
![image](https://user-images.githubusercontent.com/1025927/31555133-2be293f2-b040-11e7-859c-9eaff7c841a9.png)

Can be reproduced in TeamCity 2017.1 and 2017.2 EAP.

**Comment by Red-Folder** [comment]
@dtretyakov I am seeing a similar duplication of test results from dotnet test

You've marked this (and the referenced issue) as closed.  Can you tell me if there has been a fix?  And if so, which version would it be in?

Please let me know if you need me to share more about the details of my issue (repo, logs, versions, etc)

**Comment by dtretyakov** [comment]
@Red-Folder, currently you could [download snapshot plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityDotnetCorePluginBuild&guest=1) with a fix.

**Comment by Red-Folder** [comment]
@dtretyakov Worked perfectly.  Problem solved.  Much thanks

**Comment by cod7alex** [comment]
was the fix for this issue released?

**Comment by dtretyakov** [comment]
@cod7alex, yes for TeamCity 2017.1.x you could download the latest plugin version from https://plugins.jetbrains.com/plugin/9190--net-cli-support

TeamCity 2017.2 [has bundled .NET CLI plugin](https://www.jetbrains.com/teamcity/whatsnew/#v2017-2-net-cli-support) with a fix.

**Comment by cod7alex** [comment]
@dtretyakov thank you very much

**Comment by 0xced** [comment]
I had the exact same problem but with the *Visual Studio Tests* runner (VSTest 2017) on TeamCity 2019.1 (build 65998) where it would report duplicate tests.

I switched to use the *.NET CLI (dotnet)* runner with the `vstest` command and now the reported number of tests by TeamCity is correct.

**Comment by NPadrutt** [comment]
exactly the same as @0xced
