### ISSUE TITLE
Missing wiki page in help link

### ISSUE THREAD

**Issue by mbenua-mparticle** [JetBrains/teamcity-dotnet-plugin#92]
On the Admin\Tools settings management page, the Help (?) button doesn't work.
![image](https://user-images.githubusercontent.com/25666582/31565568-19167fd2-b01c-11e7-9c2f-e32280e2d1f4.png)

It goes to here, which is a 404: https://confluence.jetbrains.com/display/TCD10/DotnetIntegration

**Comment by dtretyakov** [comment]
@mbenua-mparticle, thanks for reporting. In the next version "Dotnet Integration" tool will be bundled in .NET CLI plugin, so dedicated documentation page for it would not be created.
